### ISSUE TITLE
Allowing blank option silently fails validation

### ISSUE THREAD

**Issue by jlawrence-yellostudio** [elivz/craft-single-cat#10]
Hi @elivz 

I'm using this in a matrix within a supertable and if I set the single category field to required and then choose the blank option it silently fails. I get an indication that the error is on that page and the matrix block has vanished.

Arguably now thinking about it further maybe the blank option is redundant given that that is what the required flag on the field does? Can you elaborate on the purpose of it?

**Comment by elivz** [comment]
Hmm, interesting. I will check that out as soon as I get a chance (probably this weekend). The reason for having the blank option is to force people to make a choice (rather than just defaulting to whatever item is first). But it shouldn't remove the Matrix row if it fails validation. I will figure out what's going on.

**Comment by elivz** [comment]
I'm afraid I haven't been able to replicate what you are describing. I might have misunderstood the situation, but I created a SuperTable field with a  Matrix inside it with a Single Category field inside that. I set all three levels to "required". When I leave the category field blank, I get a red error message, as I would expect. See screenshot below. Am I doing something differently from what you have?

<img width="661" alt="Screen Shot 2019-06-01 at 3 31 08 PM" src="https://user-images.githubusercontent.com/62592/58752750-5351de80-8482-11e9-885d-ecfce189b40a.png">
